--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/victoriovm/ItemCommand
projects:
  ItemCommand:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.0.0
...
