name: "ItemCommand"
author: "victoriovm"
api: 5.0.0
version: 1.0.0
main: victoriovm\ItemCommand\Main
description: "A simple plugin for PocketMine-MP to create interaction items"

permissions: 
  itemcommand.command:
    default: op